[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minpaas"
version = "0.1.0"
dependencies = [
  "fastapi",
  "uvicorn",
  "requests"
]

[project.scripts]
minpaas = "minpaas.cli.cli:main"

[tool.setuptools]
packages = ["minpaas"]
